apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: roboshop
    tier: backend
    environment: dev
    component: mysql
    purpose: service_demo
spec:
  containers:
    - name: nginx
      image: nginx
  