apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels:
    name: roboshop
    purpose: resources_requests_limits
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests: 
        memory:
        cpu: "60Mi"
      limits: "100m"
        memory: "120Mi"
        cpu: "150m"


