apiVersion: v1
kind: Pod
metadata:
  name: pod-config
  labels:
    purpose: config_demo
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
      - configMapRef:
          name: pod-config-ref