apiVersion: v1
kind: Service
metadata:
  name: nginx_service
  labels:
    purpose: service_demo
spec:
  selectors:
    purpose: service_demo
    project: roboshop
    environment: dev
  ports:
    protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx_pod
  labels:
    purpose: service_demo
    project: roboshop
    environment: dev
spec:
  containers:
    - name: nginx_container
      image: nginx