apiVersion: v1
kind: Service
metadata:
  name: nginx-nps
  labels:
    purpose: nodeport-demo
spec:
  type: NodePort
  selector:
    purpose: nodeport-demo
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-npp
  labels:
    purpose: nodeport-demo
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
