apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    purpose: nginx-demo-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: nginx-demo-rs
      project: roboshop
      environment: dev
  template:
    metadata: 
      labels:
        purpose: nginx-demo-rs
        project: roboshop
        environment: dev
    spec:
      containers:
        - name: nginx
          image: nginx