apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-headless
spec:
  selector:
    purpose: service_demo
    project: roboshop
    environment: dev
  clusterIP: None  # This makes the service headless
  ports:
    - port: 80
      name: web

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    purpose: service_demo
spec:
  selector:
    purpose: service_demo
    project: roboshop
    environment: dev
  ports:  
    port: 80
    name: web

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  selector:
    matchLabels:
      purpose: service_demo
      project: roboshop
      environment: dev # has to match .spec.template.metadata.labels
  serviceName: "nginx-svc-headless"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        purpose: service_demo
        project: roboshop
        environment: dev # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "efs-sc"
      resources:
        requests:
          storage: 1Gi