apiVersion: v1
kind: Service
metadata:
  name: my-headless-service
spec:
  selector:
    purpose: service_demo
    project: roboshop
    environment: dev
  clusterIP: None  # This makes the service headless
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    purpose: service_demo
spec:
  selector:
    purpose: service_demo
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      purpose: service_demo
      project: roboshop
      environment: dev # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        purpose: service_demo
        project: roboshop
        environment: dev # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.24
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "efs-sc"
      resources:
        requests:
          storage: 1Gi